export const GET_TODO_LIST = 'GET_TODO_LIST';
export const GET_TODO_LIST_SUCCESS = 'GET_TODO_LIST_SUCCESS';
export const GET_TODO_LIST_ERROR = 'GET_TODO_LIST_ERROR';

export const UPDATE_ITEM = 'UPDATE_ITEM';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_ERROR = 'UPDATE_ITEM_ERROR';

export const DELETE_ITEM = 'DELETE_ITEM';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_ERROR = 'DELETE_ITEM_ERROR';

export const CREATE_ITEM = 'CREATE_ITEM';
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';
export const CREATE_ITEM_ERROR = 'CREATE_ITEM_ERROR';

export const SELECT_ITEM = 'SELECT_ITEM';
export const UPDATE_VIEW_ITEM_FORM = 'UPDATE_VIEW_ITEM_FORM'
export const CLEAR_VIEW_ITEM_FORM = 'CLEAR_VIEW_ITEM_FORM'

export const UPDATE_ADD_ITEM_FORM = 'UPDATE_ADD_ITEM_FORM';
export const CLEAR_ADD_ITEM_FORM = 'CLEAR_ADD_ITEM_FORM';

export const APPLY_FILTER = 'APPLY_FILTER';
